#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0

import { execSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SPEC = resolve(ROOT, 'openapi.yaml');
const OUT = resolve(ROOT, 'src', 'types.ts');

const HEADER =
  '// SPDX-License-Identifier: Apache-2.0\n' +
  '// AUTOGENERATED by openapi-typescript. Do not edit by hand.\n' +
  '// Regenerate: pnpm --filter @document-chat/contracts run generate\n' +
  '\n';

console.log(`Generating types: ${SPEC} -> ${OUT}`);

execSync(`npx --no-install openapi-typescript "${SPEC}" -o "${OUT}"`, {
  cwd: ROOT,
  stdio: 'inherit',
});

const generated = await readFile(OUT, 'utf8');
if (!generated.startsWith(HEADER)) {
  await writeFile(OUT, HEADER + generated, 'utf8');
}

console.log('Done.');
